name: Build Deploy
on: [push]
jobs:
        build:
                name: Build
                runs-on: ubuntu-latest
                steps:
                        - name: yarn install
                          run: yarn install
                        - name: build
                          run: make prod
