name: Build Deploy
on: [push]
jobs:
        build:
                name: Build Deploy
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v2
                        - name: yarn install
                          run: yarn install
                        - name: work around parcel requiring global elm
                          run: sudo yarn global add elm --prefix /usr/local
                        - name: build
                          run: parcel build index.html
                        - uses: peaceiris/actions-gh-pages@v3
                          with:
                                  deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
                                  publish_dir: ./dist
